org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

android.useAndroidX=true

# Flutter migrator settings
android.builtInKotlin=false
android.newDsl=false

# Prevent Kotlin incremental cache errors caused by
# project files and Pub Cache being on different Windows drives.
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false